### ISSUE TITLE
Add JSDoc Comments

### ISSUE THREAD

**Issue by bobbyg603** [BugSplat-Git/bugsplat-js#56]

**Comment by patlehmann1** [comment]
Just wondering why you would need JSDoc comments when this repo is written entirely in TypeScript? Seems a little redundant to me.

**Comment by bobbyg603** [comment]
@zmrl010  care to chime in? What are you doing the other day where this would’ve helped?

**Comment by zmrl010** [comment]
Hi @patlehmann1 ,

I was the one who suggested JSDoccomments for this lib. I made the suggestion because while we do have all the typing information through typescript, JSDoc comments are capable of providing more than just types. They can provide a description, usage examples, links to extended documentation, etc. Most major IDEs support JSDoc in some fashion. In particular I use VSCode and PyCharm a lot and they both show JSDocs on hover for just about anything that has them. You can even JSDoc on interface properties, which is something I like to do for documenting exported interfaces.

Because the library is written typescript, I was planning on omitting the types out of the JSDoc comments anyways. The main goal is to get some descriptions for most exports. I plan on getting this done sometime this week

Hope that answers it for you!
